apiVersion: apps/v1
kind: Deployment
metadata:
  name: siconfview-deployment

#ESPECIFICAÇÃO DAS REPLICAS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siconfview-pod

  #ESPECIFICAÇÃO DO POD
  template:
    metadata:
      labels:
        app: siconfview-pod
    spec:
      imagePullSecrets:
        - name: docker-registry-ssp
      containers:
        - name: siconfview-container
          image: docker.ssp.go.gov.br/ssp/siconfview:{{COMMIT_ID}}
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
